// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlas3QIhSBmBrRIkFMncgjwM0jIaWZCdg',
    appId: '1:229012469608:web:5c1466c0a8a42ebafe48dd',
    messagingSenderId: '229012469608',
    projectId: 'car-anti-theft',
    authDomain: 'car-anti-theft.firebaseapp.com',
    databaseURL: 'https://car-anti-theft-default-rtdb.firebaseio.com',
    storageBucket: 'car-anti-theft.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUeV47Vnj3IxTtFmuifN-8hX5cTiSu9bU',
    appId: '1:229012469608:android:da0c83b6998c87dcfe48dd',
    messagingSenderId: '229012469608',
    projectId: 'car-anti-theft',
    databaseURL: 'https://car-anti-theft-default-rtdb.firebaseio.com',
    storageBucket: 'car-anti-theft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf8WFQuIr-wl1RBR9fjHfEsm-PLqjFKAA',
    appId: '1:229012469608:ios:403cf3c3179ee792fe48dd',
    messagingSenderId: '229012469608',
    projectId: 'car-anti-theft',
    databaseURL: 'https://car-anti-theft-default-rtdb.firebaseio.com',
    storageBucket: 'car-anti-theft.appspot.com',
    iosBundleId: 'com.example.cartheftsafety',
  );
}
